function [morphed_im] = morph_tps_wrapper(im1, ...
                                          im2, ...
                                          im1_pts, ...
                                          im2_pts, ...
                                          warp_frac, ...
                                          dissolve_frac)

end
