function [morphed_im] = morph_tps(im_source, ...
                                  a1_x, ...
                                  ax_x, ...
                                  ay_x, ...
                                  w_x, ...
                                  a1_y, ...
                                  ax_y, ...
                                  ay_y, ...
                                  w_y, ...
                                  ctr_pts, ...
                                  sz)

morphed_im = ones(sz);

end
