function [morphed_im] = morph_tps(im_source, ...
                                  a1_x, ...
                                  ax_x, ...
                                  ay_x, ...
                                  w_x, ...
                                  a1_y, ...
                                  ax_y, ...
                                  ay_y, ...
                                  w_y, ...
                                  ctr_pts, ...
                                  sz)

z1 = size(P, #);  % TODO(brwr)
z2 = size(P, #);  % TODO(brwr)
A = [K, P; P', zeros(z1, z2)];
w = [w ax ay a1]';
v = A * w;

morphed_im = im_source;

end
